### ISSUE TITLE
Warnings related to *

### ISSUE THREAD

**Issue by frankier** [CSCfi/hpc-container-wrapper#21]
Hi, I'm running tykky in Mahti, and get the following when making a new environment:

> WARNING conda.models.version:get_matcher(548): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .*Retrieving notices: ...working... done
Collecting package metadata (repodata.json): ...working... WARNING conda.models.version:get_matcher(548): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0

My env.yaml does not contain any "*" specifiers. Is it possible that tykky is adding them in? Could these be updated for new versions of Conda?

**Comment by Nortamo** [comment]
Hi,

The tool does not do anything to the supplied environment file, just passes it directly to conda. 
So a transitive dependency might be causing the warning?. Are you able to share the environment file?

Also for future issues directly related to the CSC computing environment, you can be directly in contact with the service desk. The issues here are not as actively monitored, so getting a response can be a bit slow.

**Comment by frankier** [comment]
Ah I see. I was a bit quick to assume where the issue was coming from. I think the issue might be https://github.com/conda/conda/issues/12330 . For some reason I didn't find that before when searching. I guess it might be possible to not use requirements.txt? Or else wait until Conda fixes it? I guess the latter is probably the most sensible option so will close this now.
